#!/bin/bash
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
sed -i 's/^ZSH_THEME.*/ZSH_THEME="strug"/' ~/.zshrc
sudo pacman -S plasma sddm kde-applications mc gnome-keyring xf86-input-synaptics
yay google-chrome
yay timeshift
yay vlc 
yay telegram
sudo systemctl enable sddm
yay vs code

git config --global user.name "max"
git config --global user.email mchernikovv@gmail.com
